import React from "react";
import HomePage from "./(pages)/HomePage";

export const metadata = {
  title: "Music App",
  description: "Generated by Gaurav",
};
export default function Home() {
  return (
    <div className="">
      <HomePage/>
    </div>
  );
}
